[tool.black]
line-length = 79

[tool.isort]
profile = "black"
line_length = 79
multi_line_output = 3

[tool.mypy]
disallow_untyped_defs = true
disallow_any_explicit = true
ignore_missing_imports = true
warn_unused_ignores = true
show_column_numbers = true
pretty = true
show_error_codes = true

[tool.coverage.run]
omit = ["gridsync/_version.py"]


[tool.ruff]
target-version = "py310"
line-length = 79
select = [
    "C90",  # mccabe
    "E",    # pycodestyle error
    "F",    # Pyflakes
    "W",    # pycodestyle warning
]
ignore = [
    "E501",  # Line too long
]

[tool.ruff.per-file-ignores]
"gridsync/core.py" = ["E402"]  # Module level import not at top of file

[tool.ruff.mccabe]
max-complexity = 10


[tool.pylint.messages_control]
disable = [
    "consider-using-f-string",
    "duplicate-code",
    "fixme",
    "import-outside-toplevel",
    "invalid-name",
    "missing-docstring",
    "no-name-in-module",
    "no-member",
    "protected-access",
    "too-few-public-methods",
    "too-many-branches",
    "too-many-instance-attributes",
    "too-many-locals",
    "too-many-public-methods",
    "too-many-statements",
    "unbalanced-tuple-unpacking",
    "wrong-import-position",
]

[tool.pytest.ini_options]
testpaths = [
    "tests",
]
addopts = "-rs -s -m \"not slow\" --ignore=tests/integration --cov-append --cov-report=html --cov=gridsync"

# Configure pytest to ignore ResourceWarning as a work-around for
# https://github.com/gridsync/gridsync/issues/479 /
# https://github.com/python/cpython/issues/91351
#
# https://docs.pytest.org/en/stable/how-to/capture-warnings.html
filterwarnings = [
    "ignore::ResourceWarning",
]
